[package]
name = "laos-bridge-runtime-common"
version = "0.1.0"
authors = ["Freeverse"]
edition = "2021"

[dependencies]
xcm = { git = "https://github.com/paritytech/polkadot", branch = "release-v1.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"xcm/std",
]
